// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travellers_Agent.Models;

#nullable disable

namespace Travellers_Agent.Migrations
{
    [DbContext(typeof(AgentsContext))]
    partial class AgentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Travellers_Agent.Models.SpotImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TourPackagespackage_id")
                        .HasColumnType("int");

                    b.Property<string>("image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_id")
                        .HasColumnType("int");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourPackagespackage_id");

                    b.ToTable("spot");
                });

            modelBuilder.Entity("Travellers_Agent.Models.TourPackages", b =>
                {
                    b.Property<int?>("package_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("package_id"));

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotel_nearby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itenary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("price")
                        .HasColumnType("int");

                    b.Property<string>("speciality_of_the_place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spots_nearby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("vacation_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("package_id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Travellers_Agent.Models.SpotImages", b =>
                {
                    b.HasOne("Travellers_Agent.Models.TourPackages", "TourPackages")
                        .WithMany("spot")
                        .HasForeignKey("TourPackagespackage_id");

                    b.Navigation("TourPackages");
                });

            modelBuilder.Entity("Travellers_Agent.Models.TourPackages", b =>
                {
                    b.Navigation("spot");
                });
#pragma warning restore 612, 618
        }
    }
}
